### ISSUE TITLE
module broken ?

### ISSUE THREAD

**Issue by franck34** [Kikobeats/knox-steroids#2]
I don't speak coffee script :(

Using node v6.10.1, your module does NOT expose your magic functions.

```
var knox = require('knox-steroids');

var client = knox.createClient({
    "key": "xxxxxxxxxxxxx",
    "secret": "xxxxxxxxxxxxxxx/Y",
    "bucket": "xxxxxxxx"
});

console.log(client.deleteFolder);
```

actual
```
undefined
```

expected
```
[Function]
```

Thank you

**Comment by Kikobeats** [comment]
Hi, currently I'm not maintaining this library, so no idea ¯\_(ツ)_/¯

**Comment by franck34** [comment]
Yep, switching back to knox native. Should be great if you can put a deprecated warning in your README ;)

Thank you

**Comment by Kikobeats** [comment]
It's not deprecated, simply I'm not using/Maintain it.

**Comment by franck34** [comment]
It's deprecated because it just does not work. And there is no tests provided. Not serious. But thanks for your work.

deleteFolder alternative old school code here:

https://gist.github.com/franck34/b1ab4c7ecf27023a2f68320ba6a3fd0a
